import { StyleSheet, Dimensions, Platform } from 'react-native';
import { Colors } from '@constants/Colors';

const { width } = Dimensions.get('window');
// Calculate width for a 3-column grid with dynamic spacing
const cardWidth = (width - 40 - 20) / 3; 

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f1f1',
  },
  backButton: {
    padding: 5,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.text,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  statsCard: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 3,
  },
  statsTextContainer: {
    flex: 1,
    marginRight: 15,
  },
  statsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.text,
    marginBottom: 4,
  },
  statsSub: {
    fontSize: 12,
    color: Colors.textLight,
    lineHeight: 16,
  },
  statsCircle: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: 'rgba(255, 107, 107, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: Colors.primary,
  },
  statsProgressText: {
    fontSize: 16,
    fontWeight: '800',
    color: Colors.primary,
  },
  statsProgressLabel: {
    fontSize: 8,
    color: Colors.textLight,
    fontWeight: '600',
    marginTop: 2,
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: '#ECEFF1',
    borderRadius: 25,
    padding: 4,
    marginBottom: 20,
  },
  tab: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 20,
  },
  activeTab: {
    backgroundColor: Colors.white,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textLight,
  },
  activeTabText: {
    color: Colors.text,
    fontWeight: '700',
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    marginHorizontal: -5,
  },
  emptyText: {
    flex: 1,
    fontSize: 14,
    color: Colors.textLight,
    fontStyle: 'italic',
    textAlign: 'center',
    marginTop: 30,
  },
  badgeCard: {
    width: cardWidth,
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    marginBottom: 15,
    marginHorizontal: 3.3,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1.5,
  },
  earnedBadgeCard: {
    borderColor: 'transparent',
  },
  lockedBadgeCard: {
    borderColor: 'transparent',
    opacity: 0.85,
  },
  badgeIconContainer: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  earnedIconBg: {
    backgroundColor: '#FFF0F0',
    borderWidth: 1.5,
    borderColor: '#FFE3E3',
  },
  lockedIconBg: {
    backgroundColor: '#ECEFF1',
    borderWidth: 1.5,
    borderColor: '#CFD8DC',
  },
  badgeIcon: {
    fontSize: 26,
  },
  lockedIconOverlay: {
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  lockMiniIcon: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: Colors.white,
    width: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    lineHeight: 18,
    borderWidth: 1,
    borderColor: '#CFD8DC',
    overflow: 'hidden',
  },
  badgeName: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.text,
    textAlign: 'center',
    marginBottom: 4,
    height: 32, // Allow 2 lines of text
  },
  badgeRequirement: {
    fontSize: 8.5,
    color: Colors.textLight,
    textAlign: 'center',
    width: '100%',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(45, 52, 54, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '90%',
    backgroundColor: Colors.white,
    borderRadius: 25,
    padding: 25,
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 10,
    position: 'relative',
  },
  closeButton: {
    position: 'absolute',
    top: 15,
    right: 15,
    zIndex: 10,
    padding: 5,
  },
  detailContainer: {
    alignItems: 'center',
    width: '100%',
    paddingTop: 10,
  },
  detailIconBg: {
    width: 90,
    height: 90,
    borderRadius: 45,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  earnedDetailIconBg: {
    backgroundColor: '#FFF0F0',
    borderWidth: 2,
    borderColor: '#FFE3E3',
  },
  lockedDetailIconBg: {
    backgroundColor: '#ECEFF1',
    borderWidth: 2,
    borderColor: '#CFD8DC',
  },
  detailEmoji: {
    fontSize: 46,
  },
  detailLockedWrapper: {
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  detailLockIcon: {
    position: 'absolute',
    alignSelf: 'center',
  },
  detailName: {
    fontSize: 20,
    fontWeight: '800',
    color: Colors.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  statusTag: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 15,
  },
  earnedStatusTag: {
    backgroundColor: 'rgba(85, 239, 196, 0.15)',
  },
  lockedStatusTag: {
    backgroundColor: 'rgba(99, 110, 114, 0.1)',
  },
  statusTagText: {
    fontSize: 11,
    fontWeight: '700',
  },
  earnedStatusTagText: {
    color: '#00B894',
  },
  lockedStatusTagText: {
    color: Colors.textLight,
  },
  detailDescription: {
    fontSize: 14,
    color: Colors.textLight,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  requirementBox: {
    width: '100%',
    backgroundColor: Colors.background,
    borderRadius: 14,
    padding: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#eee',
  },
  reqTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.textLight,
    marginBottom: 4,
  },
  reqText: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.text,
  },
  earnedDate: {
    fontSize: 11,
    color: Colors.textLight,
    fontStyle: 'italic',
    marginBottom: 20,
  },
  actionButton: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  earnedActionButton: {
    backgroundColor: Colors.primary,
  },
  lockedActionButton: {
    backgroundColor: '#B2BEC3',
  },
  actionButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: Colors.white,
  },
  errorText: {
    fontSize: 15,
    color: Colors.textLight,
    marginTop: 10,
    marginBottom: 20,
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  retryText: {
    color: Colors.white,
    fontWeight: '600',
    fontSize: 14,
  },
});
