import { StyleSheet, Platform } from 'react-native';
import { Colors } from '@constants/Colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: 15,
    backgroundColor: Colors.white,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: Colors.text,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 15,
  },
  searchIcon: {
    position: 'absolute',
    left: 35,
    zIndex: 1,
  },
  searchInput: {
    flex: 1,
    height: 50,
    backgroundColor: Colors.white,
    borderRadius: 15,
    paddingLeft: 45,
    paddingRight: 20,
    fontSize: 15,
    color: Colors.text,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  sectionHeader: {
    paddingHorizontal: 20,
    marginTop: 25,
    marginBottom: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.text,
  },
  keywordsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 15,
  },
  keywordBadge: {
    backgroundColor: Colors.white,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    margin: 5,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  keywordText: {
    fontSize: 14,
    color: Colors.text,
    fontWeight: '500',
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 15,
  },
  categoryGridItem: {
    width: '46%',
    aspectRatio: 1,
    margin: '2%',
    borderRadius: 20,
    overflow: 'hidden',
  },
  categoryImage: {
    width: '100%',
    height: '100%',
  },
  categoryOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryName: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  searchResultsSection: {
    paddingHorizontal: 20,
    marginTop: 10,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    padding: 12,
    borderRadius: 15,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  resultImage: {
    width: 60,
    height: 60,
    borderRadius: 12,
  },
  resultInfo: {
    flex: 1,
    marginLeft: 15,
  },
  resultTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.text,
  },
  resultMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  resultMetaText: {
    fontSize: 12,
    color: Colors.textLight,
    marginLeft: 4,
  },
  noResultsText: {
    textAlign: 'center',
    color: Colors.textLight,
    marginTop: 20,
    fontSize: 15,
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 15,
    fontSize: 14,
    color: Colors.textLight,
    fontStyle: 'italic',
  },
  activeKeywordBadge: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  activeKeywordText: {
    color: Colors.white,
  },
  magicCard: {
    marginHorizontal: 16,
    backgroundColor: Colors.primary,
    borderRadius: 24,
    flexDirection: 'row',
    height: 180,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 8,
    overflow: 'hidden',
    marginBottom: 12
  },
  magicContent: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  magicHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  magicTag: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginRight: 8,
  },
  magicTitle: {
    color: Colors.white,
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  magicDesc: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 15,
  },
  magicButton: {
    backgroundColor: Colors.white,
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  magicButtonText: {
    color: Colors.primary,
    fontWeight: 'bold',
    fontSize: 13,
  },
  magicImage: {
    width: '35%',
    height: '100%',
    opacity: 0.9,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 25,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 25,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.text,
  },
  ingredientsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -5,
  },
  ingredientItem: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 15,
    backgroundColor: '#F5F5F5',
    margin: 5,
    borderWidth: 1,
    borderColor: '#EEEEEE',
  },
  ingredientItemSelected: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  ingredientText: {
    fontSize: 14,
    color: Colors.text,
  },
  ingredientTextSelected: {
    color: Colors.white,
    fontWeight: '600',
  },
  suggestButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 18,
    borderRadius: 20,
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 10,
  },
  suggestButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  ingredientsSummary: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 15,
  },
  ingChip: {
    backgroundColor: '#E3F2FD',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  ingChipText: {
    fontSize: 12,
    color: Colors.primary,
    fontWeight: '600',
  },
  customInputContainer: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  customInput: {
    flex: 1,
    height: 50,
    backgroundColor: '#F5F5F5',
    borderRadius: 15,
    paddingHorizontal: 20,
    fontSize: 15,
    color: Colors.text,
    borderWidth: 1,
    borderColor: '#EEEEEE',
  },
  addCustomButton: {
    width: 50,
    height: 50,
    backgroundColor: Colors.primary,
    borderRadius: 15,
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalScroll: {
    maxHeight: 300,
  },
  matchBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#4CAF50',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  matchText: {
    color: Colors.white,
    fontSize: 10,
    fontWeight: 'bold',
  },
  syncStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 10,
    backgroundColor: '#F0F7FF',
    paddingVertical: 10,
    marginHorizontal: 20,
    borderRadius: 12,
  },
  syncStatusText: {
    fontSize: 13,
    color: Colors.secondary,
    marginLeft: 10,
    fontStyle: 'italic',
  },
  promoCard: {
    marginHorizontal: 20,
    marginTop: 30,
    backgroundColor: '#E3F2FD',
    borderRadius: 25,
    flexDirection: 'row',
    overflow: 'hidden',
    height: 160,
  },
  promoInfo: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  promoTag: {
    color: Colors.secondary,
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  promoTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.text,
  },
  promoDesc: {
    fontSize: 12,
    color: Colors.textLight,
    marginTop: 4,
    marginBottom: 12,
  },
  promoButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 10,
    alignSelf: 'flex-start',
  },
  promoButtonText: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
  promoImage: {
    width: '40%',
    height: '100%',
  },
  searchBarContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
});
