import { StyleSheet, Platform, Dimensions } from 'react-native';
import { Colors } from '@constants/Colors';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: 15,
    backgroundColor: Colors.white,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: Colors.text,
  },
  createButton: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  feedList: {
    paddingBottom: 20,
  },
  tabsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginTop: 15,
    marginBottom: 10,
  },
  tab: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 10,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  activeTab: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.textLight,
  },
  activeTabText: {
    color: Colors.white,
  },
  // Image Picker
  imagePickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  imagePickerBtn: {
    width: 80,
    height: 80,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.primary,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    backgroundColor: 'rgba(255, 107, 107, 0.05)',
  },
  imagePickerBtnText: {
    fontSize: 10,
    color: Colors.primary,
    fontWeight: 'bold',
    marginTop: 5,
  },
  previewImageContainer: {
    marginRight: 10,
    position: 'relative',
  },
  previewImage: {
    width: 80,
    height: 80,
    borderRadius: 10,
  },
  removeImageBtn: {
    position: 'absolute',
    top: -5,
    right: -5,
  },
  statText: {
    fontSize: 14,
    color: Colors.text,
    marginLeft: 5,
    fontWeight: '500',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.text,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.text,
    marginTop: 15,
    marginBottom: 10,
  },
  searchMiniInput: {
    backgroundColor: '#F1F3F5',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    color: Colors.text,
    marginBottom: 10,
  },
  recipePicker: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  recipeOption: {
    width: 120,
    marginRight: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 8,
    alignItems: 'center',
  },
  selectedRecipeOption: {
    borderColor: Colors.primary,
    backgroundColor: 'rgba(255, 107, 107, 0.05)',
  },
  recipeOptionImage: {
    width: 100,
    height: 80,
    borderRadius: 10,
    marginBottom: 5,
  },
  recipeOptionText: {
    fontSize: 12,
    color: Colors.textLight,
    textAlign: 'center',
  },
  selectedRecipeOptionText: {
    color: Colors.primary,
    fontWeight: 'bold',
  },
  ratingPicker: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  textInput: {
    backgroundColor: '#F8F9FA',
    borderRadius: 15,
    padding: 15,
    fontSize: 16,
    color: Colors.text,
    height: 120,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  postButton: {
    backgroundColor: Colors.primary,
    borderRadius: 15,
    padding: 18,
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 20,
  },
  postButtonText: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  suggestedSection: {
    paddingVertical: 15,
    backgroundColor: Colors.white,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.text,
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  usersScroll: {
    paddingLeft: 20,
  },
  userCard: {
    width: 130,
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 15,
    marginRight: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  userAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginBottom: 10,
  },
  userFullName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: Colors.text,
    marginBottom: 10,
    textAlign: 'center',
  },
  followSmallButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 15,
    paddingVertical: 6,
    borderRadius: 15,
  },
  followSmallButtonText: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
});
