import { StyleSheet, Platform, Dimensions } from 'react-native';
import { Colors } from '@constants/Colors';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: 10,
    backgroundColor: Colors.white,
  },
  greeting: {
    fontSize: 16,
    color: Colors.textLight,
    fontWeight: '500',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: Colors.text,
    marginTop: 4,
  },
  notificationButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.primary,
    borderWidth: 2,
    borderColor: Colors.white,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  searchContainer: {
    marginTop: 15,
    marginBottom: 5,
  },
  searchIcon: {
    position: 'absolute',
    left: 35,
    zIndex: 1,
  },
  searchInput: {
    flex: 1,
    height: 50,
    backgroundColor: Colors.white,
    borderRadius: 15,
    paddingLeft: 45,
    paddingRight: 20,
    fontSize: 15,
    color: Colors.text,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  filterButton: {
    width: 50,
    height: 50,
    backgroundColor: Colors.primary,
    borderRadius: 15,
    marginLeft: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 30,
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.text,
  },
  seeAllText: {
    fontSize: 14,
    color: Colors.primary,
    fontWeight: '600',
  },
  categoriesList: {
    paddingLeft: 20,
    paddingRight: 10,
  },
  categoryCard: {
    alignItems: 'center',
    marginRight: 20,
  },
  categoryIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  categoryName: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.text,
  },
  featuredGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  recipeCardWrapper: {
    width: '48%',
    marginBottom: 15,
  },
  recipeCard: {
    width: '100%',
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 15,
    justifyContent: 'space-between',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  recipeCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  recipeBadge: {
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  recipeBadgeText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: Colors.primary,
  },
  favoriteButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F8F9FA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  recipeInfo: {
    marginTop: 'auto',
  },
  recipeTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.text,
    marginBottom: 8,
  },
  recipeMeta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  recipeMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 15,
  },
  recipeMetaText: {
    fontSize: 12,
    color: Colors.textLight,
    marginLeft: 4,
    fontWeight: '500',
  },
  recommendationWrapper: {
    marginTop: 15,
  },
  recommendationCard: {
    width: SCREEN_WIDTH - 40,
    marginHorizontal: 20,
    backgroundColor: '#FFF0F0',
    borderRadius: 25,
    padding: 20,
    shadowOffset: { width: 0, height: 10 },
    borderWidth: 1,
    borderColor: '#FFE0E0',
  },
  recommendationContent: {
    flex: 1,
  },
  recommendationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  recommendationTag: {
    backgroundColor: Colors.white,
    color: Colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    fontSize: 12,
    fontWeight: 'bold',
    overflow: 'hidden',
  },
  recommendationTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.text,
    lineHeight: 28,
    marginBottom: 15,
  },
  recommendationMeta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  paginationDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#D1D1D1',
    marginHorizontal: 4,
  },
  activeDot: {
    width: 18,
    backgroundColor: Colors.primary,
  },
  aiModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  aiModalContent: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    height: '80%',
    display: 'flex',
    flexDirection: 'column',
  },
  aiModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F3F5',
  },
  aiModalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  aiModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.text,
    marginLeft: 8,
  },
  aiModalSubtitle: {
    fontSize: 11,
    color: Colors.primary,
    fontWeight: '600',
    backgroundColor: '#FFF0F0',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    marginLeft: 10,
  },
  aiMessageList: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  aiBubble: {
    maxWidth: '80%',
    padding: 14,
    borderRadius: 18,
    marginBottom: 12,
  },
  aiBubbleUser: {
    backgroundColor: Colors.primary,
    alignSelf: 'flex-end',
    borderBottomRightRadius: 4,
  },
  aiBubbleAi: {
    backgroundColor: '#F1F3F5',
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 4,
  },
  aiBubbleTextUser: {
    fontSize: 15,
    lineHeight: 20,
    color: Colors.white,
  },
  aiBubbleTextAi: {
    fontSize: 15,
    lineHeight: 20,
    color: Colors.text,
  },
  aiMessageText: {
    fontSize: 15,
    lineHeight: 20,
  },
  aiMessageTextUser: {
    color: Colors.white,
  },
  aiMessageTextAi: {
    color: Colors.text,
  },
  aiQuickPillsContainer: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderTopWidth: 1,
    borderTopColor: '#F1F3F5',
  },
  aiQuickPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  aiQuickPillText: {
    fontSize: 13,
    color: '#495057',
    marginLeft: 4,
  },
  aiInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    paddingBottom: Platform.OS === 'ios' ? 30 : 15,
    borderTopWidth: 1,
    borderTopColor: '#F1F3F5',
    backgroundColor: Colors.white,
  },
  aiInput: {
    flex: 1,
    backgroundColor: '#F1F3F5',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 15,
    color: Colors.text,
    marginRight: 10,
    maxHeight: 100,
  },
  aiSendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  aiSendButtonDisabled: {
    backgroundColor: '#CED4DA',
  },
  aiTypingBubble: {
    backgroundColor: '#F1F3F5',
    alignSelf: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 18,
    borderBottomLeftRadius: 4,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  aiTypingText: {
    fontSize: 13,
    color: '#868E96',
    marginLeft: 6,
    fontStyle: 'italic',
  },
});
